puddle/conversation/urls.py
from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path("", views.inbox, name="inbox"),
    path("new/<int:item_pk>", views.new_chat, name="new"),
    path("chat/<int:pk>", views.chat, name="chat"),
]

puddle/core/urls.py
from django.urls import path
from .views import index, contact, signup
from django.contrib.auth import views as auth_views
from .forms import LoginForm

app_name = "core"

urlpatterns = [
    path("", index, name="index"),
    path("signup/", view=signup, name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name="login.html", authentication_form=LoginForm), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

puddle/dashboard/urls.py
from django.urls import path
from .views import dashboard

app_name = "dashboard"

urlpatterns = [
    path("", dashboard, name="dashboard"),
]

puddle/item/urls.py
from django.urls import path
from .views import detail, new_item, delete_item, edit_item, browse

app_name = "item"

urlpatterns = [
    path("", view=browse, name="browse"),
    path("<int:pk>/", view=detail, name="detail"),
    path("new-item/", view=new_item, name="new_item"),
    path("delete/<int:pk>/", view=delete_item, name="delete_item"),
    path("edit/<int:pk>/", view=edit_item, name="edit_item"),

]

puddle/puddle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('items/', include("item.urls")),
    path('dashboard/', include("dashboard.urls")),
    path("inbox/", include("conversation.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

puddle/core/models.py
from django.db import models

# Create your models here.

puddle/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder' : 'Enter Your Username',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'Enter Your Password',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder' : 'Enter Your Username',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder' : 'Enter Your Email Address',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'Enter Your Password',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'Repeat Password',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))

puddle/core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item 
from .forms import SignupForm
from django.urls import reverse

def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render(request, "index.html", {
        'categories' : categories,
        'items' : items,
    })

def contact(request):
    return render(request, "contact.html")

def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("core:login"))
    else:
        form = SignupForm()
    return render(request, 'signup.html', {'form' : form})

puddle/core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}  {% endblock %} | Puddle</title>
</head>
<body>
    <nav class="p-6 flex justify-between items-center flex-wrap gap-y-2 border-b border-gray-200">
        <a href="/" class="text-2xl font-semibold">Puddle</a>
        <div class="flex flex-wrap flex gap-3 items-center">
            <a href="{% url 'item:browse' %}" class="px-4 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">
                Browse Catalogue
            </a>

            {% if request.user.is_authenticated %}
                <a href="{% url 'chat:inbox' %}" class="px-4 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">
                    Inbox
                </a>
                <a href="{% url 'dashboard:dashboard' %}" class="px-4 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">
                    My Dashboard
                </a>
                <a href="{% url 'item:new_item' %}" class="px-4 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">
                    Sell Item
                </a>
                    <!-- <div class="text-right font-medium block">
                        Welcome, {{ request.user.username }}!
                    </div> -->
                <a href="{% url 'core:logout' %}" class="px-3 py-2 text-md font-medium bg-yellow-500 text-white rounded-xl hover:bg-yellow-700">
                    Logout as {{ request.user.username }} 
                </a>

            {% else %}
                <a href="{% url 'core:signup' %}" class="px-4 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">
                    Sign Up
                </a>
                <a href="{% url 'core:login' %}" class="px-4 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">
                    Login
                </a>
            {% endif %}

        </div>
    </nav>
    {% block content %}
    {% endblock %}
    <footer class="p-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">
                About
            </h3>
            <p class="text-lg text-gray-500">
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae natus veritatis eaque! Et vel eligendi perferendis tenetur id, illum alias animi officia, amet sit aperiam modi a minima veritatis quia.
            </p>
        </div>
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">
                Menu
            </h3>
            <ul class="space-y-2">
                <li>
                    <a href="#" class="text-base text-teal-500 hover:text-teal-700">
                        About
                    </a>
                </li>
                <li>
                    <a href="#" class="text-base text-teal-500 hover:text-teal-700">
                        Contact
                    </a>
                </li>
                <li>
                    <a href="#" class="text-base text-teal-500 hover:text-teal-700">
                        Privacy Policy
                    </a>
                </li>
                <li>
                    <a href="#" class="text-base text-teal-500 hover:text-teal-700">
                        Tearms Of Use
                    </a>
                </li>
            </ul>
        </div>
    </footer>
</body>
</html>

puddle/core/templates/index.html
{% extends "base.html" %}

{% block title %}
Welcome
{% endblock %}

{% block content %}
    <div class="px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl p-4 text-center tracking-wide bg-pink-300 font-medium shadow-lg">Newest Items</h2>
        <div class="grid gap-x-6 gap-y-8 items-center justify-items-center lg:grid-cols-3 md:grid-cols-2 sm:grid-cols-1">
            {% for item in items %}
                <div class="shadow-xl rounded-xl text-center border-4 border-transparent hover:border-4 hover:border-pink-400 hover:rounded-xl">
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url}}" class="rounded-t-xl object-scale-down h-96 w-96">
                        </div>
                        <div class="p-6 bg-teal-100 rounded-b-xl">
                            <h2 class="text-2xl"> {{item.name}} </h2>
                            <p class="text-gray-500 font-medium text-lg"> ₹ {{item.price}} </p>
                        </div>
                    </a>
                </div>
            {% endfor%}
        </div>
    </div>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl p-4 text-center tracking-wide bg-pink-300 font-medium shadow-lg">Categories</h2>
        <div class="grid gap-3 lg:grid-cols-3 md:grid-cols-2 sm:grid-cols-1">
            {% for category in categories %}
                <div>
                    <a href="{% url 'item:browse' %}?category={{ category.id }}">
                        <div class="p-6 bg-teal-100 rounded-xl border-2 border-teal-500">
                            <h2 class="text-2xl"> {{category.name}} </h2>
                            <p class="text-gray-500"> {{category.items.count }} Items </p>
                        </div>
                    </a>
                </div>
            {% endfor%}
        </div>
    </div>
{% endblock %}

puddle/core/templates/login.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}
   
{% block content %} 
<div class="min-h-[35rem] flex items-center justify-center">
    <div class="bg-gray-100 rounded-xl p-6 mx-3 w-[40rem]">
        <h1 class="mb-6 text-3xl font-semibold">Login</h1>
        <hr>
        <form method="post" action=".">
            {% csrf_token %}
            <div class="mb-3 mt-3">
                <label class="inline-block mb-2">Username</label><br>
                {{form.username}}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{form.password}}
            </div>
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            <button class="py-4 px-8 text-lg bg-teal-500 rounded-xl text-white hover:bg-teal-700">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

puddle/core/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}
   
{% block content %} 
<div class="min-h-[35rem] flex items-center justify-center">
    <div class="bg-gray-100 rounded-xl p-6 mx-3 w-[40rem]">
        <h1 class="mb-6 text-3xl font-semibold">Sign Up</h1>
        <hr>
        <form method="post" action=".">
            {% csrf_token %}
            <div class="mb-3 mt-3">
                <label class="inline-block mb-2">Username</label><br>
                {{form.username}}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Email</label><br>
                {{form.email}}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{form.password1}}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Confirm Password</label><br>
                {{form.password2}}
            </div>
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            <button class="py-4 px-8 text-lg bg-teal-500 rounded-xl text-white hover:bg-teal-700">Submit</button>
        </form>
    </div>
</div>
{% endblock %}