puddle/conversation/urls.py
from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path("", views.inbox, name="inbox"),
    path("new/<int:item_pk>", views.new_chat, name="new"),
    path("chat/<int:pk>", views.chat, name="chat"),
]

puddle/core/urls.py
from django.urls import path
from .views import index, contact, signup
from django.contrib.auth import views as auth_views
from .forms import LoginForm

app_name = "core"

urlpatterns = [
    path("", index, name="index"),
    path("signup/", view=signup, name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name="login.html", authentication_form=LoginForm), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

puddle/item/urls.py
from django.urls import path
from .views import detail, new_item, delete_item, edit_item, browse

app_name = "item"

urlpatterns = [
    path("", view=browse, name="browse"),
    path("<int:pk>/", view=detail, name="detail"),
    path("new-item/", view=new_item, name="new_item"),
    path("delete/<int:pk>/", view=delete_item, name="delete_item"),
    path("edit/<int:pk>/", view=edit_item, name="edit_item"),

]

puddle/puddle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('items/', include("item.urls")),
    path('dashboard/', include("dashboard.urls")),
    path("inbox/", include("conversation.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

puddle/item/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name;

    class Meta:
        ordering = ('name',)
        verbose_name_plural = "Categories"

class Item(models.Model):
    category = models.ForeignKey(Category, related_name="items", on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to="item_images", blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name="items", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name;

puddle/item/forms.py
from django import forms
from .models import Item

INPUT_CLASSES = 'w-full mt-2 py-4 px-6 rounded-xl'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image')
    
        widgets = {
            'category' : forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name' : forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description' : forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price' : forms.NumberInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image' : forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold')
    
        widgets = {
            'name' : forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description' : forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price' : forms.NumberInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image' : forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

puddle/item/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.db.models import Q
from item.models import Item, Category
from .forms import NewItemForm, EditItemForm
from django.contrib.auth.decorators import login_required

def browse(request):
    query = request.GET.get("query", "")
    category_id = request.GET.get("category", 0)
    order = request.GET.get("order", "")
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)

    if category_id:
        items = items.filter(category_id = category_id)

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))
    
    if order:
        items = items.order_by(order)

    return render(request, "browse.html", {
        "items" : items,
        "query" : query,
        "categories" : categories,
        "category_id" : int(category_id),
        "order" : order,
        })

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]
    return render(request, "detail.html", {
        "item" : item,
        "related_items" : related_items,
    })

@login_required
def new_item(request):
    if request.method == "POST":
        form = NewItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect("item:detail", pk=item.id)
    form = NewItemForm()
    return render(request, "item_form.html", {
        "form": form,
        "title": "New Item",
        })

@login_required
def edit_item(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)

    if request.method == "POST":
        form = EditItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()

            return redirect("item:detail", pk=item.id)
    form = EditItemForm(instance=item)
    return render(request, "item_form.html", {
        "form": form,
        "title": "Edit Item",
        })

@login_required
def delete_item(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()
    return redirect("dashboard:dashboard")

puddle/item/templates/browse.html
{% extends 'base.html' %}

{% block title %} Browse {% endblock %}

{% block content %}
    <div class="p-4 grid gap-4 bg-gray-100 lg:grid-cols-4 md:grid-cols-3 sm:grid-cols-2">
        <div class="col-span-1 max-h-screen overflow-y-auto text-center sm:text-left">
            <form method="get" action=".">
                <input name="query" class="w-full py-4 px-6 rounded-xl" type="text" value="{{ query }}" placeholder="Find clothing apperal, toys and more..">
                <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
            </form>
            <hr class="my-6">
            <p class="font-semibold pb-4"> Categories </p>
            <ul>
                {% for category in categories %}
                    <li class="p-2 rounded-xl {% if category.id == category_id %} bg-pink-200 font-medium {% endif %}">
                        <a href="{% url 'item:browse' %}?query={{ query }}&category={{ category.id }}&order={{ order }}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>
            <hr class="my-6">
            <p class="font-semibold pb-4"> Sort Items </p>
            <ul>
                <li class="p-2 rounded-xl {% if order == 'price' %} bg-pink-200 font-medium {% endif %}">
                    <a href="{% url 'item:browse' %}?query={{ query }}{% if category_id != 0 %}&category={{ category_id }}{% endif %}&order=price">Cheapest First</a>
                </li>
                <li class="p-2 rounded-xl {% if order == '-price' %} bg-pink-200 font-medium {% endif %}">
                    <a href="{% url 'item:browse' %}?query={{ query }}{% if category_id != 0 %}&category={{ category_id }}{% endif %}&order=-price">Expensive First</a>
                </li>
                <li class="p-2 rounded-xl {% if order == '-created_at' %} bg-pink-200 font-medium {% endif %}">
                    <a href="{% url 'item:browse' %}?query={{ query }}{% if category_id != 0 %}&category={{ category_id }}{% endif %}&order=-created_at">Newest First</a>
                </li>
                <li class="p-2 rounded-xl {% if order == 'created_at' %} bg-pink-200 font-medium {% endif %}">
                    <a href="{% url 'item:browse' %}?query={{ query }}{% if category_id != 0 %}&category={{ category_id }}{% endif %}&order=created_at">Oldest First</a>
                </li>
            </ul>
            <a href="{% url 'item:browse' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Reset Filters</a>
        </div>
        {% if not items %}
            <div class="m-5 text-xl font-medium">No Matches Found.</div>
        {% endif %}
        <div class="lg:col-span-3  md:col-span-2  sm:col-span-1 max-h-screen overflow-y-auto">
            <div class="grid gap-x-6 gap-y-8 items-center justify-items-center lg:grid-cols-3 md:grid-cols-2 sm:grid-cols-1">
                
                {% for item in items %}
                    <div class="shadow-xl rounded-xl text-center border-4 border-transparent hover:border-4 hover:border-pink-400 hover:rounded-xl">
                        <a href="{% url 'item:detail' item.id %}">
                            <div>
                                <img src="{{ item.image.url}}" class="rounded-t-xl object-scale-down h-96 w-96">
                            </div>
                            <div class="p-6 bg-teal-100 rounded-b-xl">
                                <h2 class="text-2xl"> {{item.name}} </h2>
                                <p class="text-gray-500 font-medium text-lg"> ₹ {{item.price}} </p>
                            </div>
                        </a>
                    </div>
                {% endfor%}
            </div>
        </div>
    </div>
{% endblock %}

puddle/item/templates/detail.html
{% extends 'base.html' %}

{% block title %} {{ item.name }} {% endblock %}

{% block content %} 
    <div class="grid gap-2 m-12 justify-items-center md:grid-cols-4 sm:grid-cols-2">
      <div class="col-span-2">
        <img src="{{ item.image.url }}" class="rounded-xl object-scale-down h-96 w-96">
      </div>
      <div class="col-span-2 p-6 bg-gray-100 rounded-xl min-w-full">
            <h1 class="mb-6 text-3xl"> {{ item.name }} </h1>
            <p class="text-gray-500 text-lg"><strong>Price: </strong>₹ {{ item.price }}</p>
            <p class="text-gray-500 text-lg"><strong>Seller: </strong>{{ item.created_by }}</p>
            
            {% if item.description %}
                <p class="text-gray-700 text-lg">
                    <strong class="text-gray-500">Description:</strong><br>
                    {{ item.description }}
                </p>
            {% endif %}
            {% if item.is_sold %}
                <p class="font-bold text-2xl text-red-700"> This Item is sold out. </p>
            {% endif %}
            {% if request.user == item.created_by %}
                <div class="mt-6 p-6 bg-white rounded-xl space-x-2">
                    <p>This is your Item. </p>
                    <a href="{% url 'item:edit_item' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Edit</a>
                    <a href="{% url 'item:delete_item' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
                </div>
            {% else %}
                <a href="{% url 'chat:new' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">
                    Contact Seller
                </a>
            {% endif %} 
      </div>
    </div>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl p-4 text-center tracking-wide bg-pink-300 font-medium shadow-lg">Related Items</h2>
        <div class="grid gap-3 items-center justify-items-center lg:grid-cols-3 md:grid-cols-2 sm:grid-cols-1">
            {% for item in related_items %}
                <div class="shadow-xl rounded-xl text-center border-4 border-transparent hover:border-4 hover:border-pink-400 hover:rounded-xl">
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url}}" class="rounded-t-xl object-scale-down h-96 w-96">
                        </div>
                        <div class="p-6 bg-teal-100 rounded-b-xl">
                            <h2 class="text-2xl"> {{item.name}} </h2>
                            <p class="text-gray-500 font-medium text-lg"> ₹ {{item.price}} </p>
                        </div>
                    </a>
                </div>
            {% endfor%}
        </div>
    </div>
{% endblock %}

puddle/item/templates/item_form.html
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}

<div class="flex flex-col justify-items-center items-center px-2 my-6 gap-6">
    <h1 class="p-4 rounded-xl text-3xl font-medium text-center bg-pink-100 lg:w-[60%] md:w-[90%] sm:w-[100%]">{{ title }}</h1>
    <form class="flex flex-col p-7 bg-gray-200 rounded-xl lg:w-[60%] md:w-[90%] sm:w-[100%]" method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        <div class="space-y-4">
            {{ form.as_p }}
        </div>
        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <button class="self-center my-6 py-4 px-8 text-lg bg-teal-500 rounded-xl text-white hover:bg-teal-700 w-32">Submit</button>
    </form>
</div> 
{% endblock %}